### ISSUE TITLE
Unable to set HTTP port in dropwizard 0.9.x

### ISSUE THREAD

**Issue by richmidwinter** [dropwizard/dropwizard#1359]
This page:

http://www.dropwizard.io/0.9.1/docs/manual/configuration.html#simple

suggest that this should work in the application yml config file:

```
  connector:
    type: http
    port: 8080
```

I'm finding it errors though.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.hasToken(Lcom/fasterxml/jackson/core/JsonToken;)Z
	at com.fasterxml.jackson.module.afterburner.deser.SettableIntMethodProperty.deserializeAndSet(SettableIntMethodProperty.java:56)
```

Seems to particularly be the port number causing the issue. Works in 0.8.5.

**Comment by joschi** [comment]
@richmidwinter Check your Jackson dependencies for incompatible versions (e. g. by running `mvn dependency:tree`).

**Comment by richmidwinter** [comment]
Good call, thanks!
