### PR TITLE
Use SslContextFactory.Server over deprecated SslContextFactory

### PR DESCRIPTION
**Pull request by MatthewRyanRead**
###### Problem:

Same as #3369:

>When we pin a more recent version of Jetty in our projects, services fail to start up with SSL with this error:
>
>```
>java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
>```

###### Solution:

Exactly the title.  Does not bump the Jetty version, but allows users to pin a later version if they so desire without any conflicts.

This is hopefully a more palatable approach than that taken in #3369 &mdash; it's definitely much simpler.

### CODE REVIEW

**Comment by MatthewRyanRead** [comment]
```
[ERROR] testHttp2WithCustomCipher(io.dropwizard.http2.Http2WithCustomCipherTest)  Time elapsed: 2.753 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: nullSession
	at io.dropwizard.http2.Http2WithCustomCipherTest.testHttp2WithCustomCipher(Http2WithCustomCipherTest.java:33)
Caused by: java.lang.NoSuchFieldError: nullSession
```

Can't figure out the cause of this ... once again, tests pass just fine locally.  Something with the travis-ci environment maybe?

**Comment by MatthewRyanRead** [comment]
Ah, Googling `java.lang.NoSuchFieldError: nullSession` is revealing.  It's an SSL issue with the 8u252 JDK.  Apparently newer versions of Jetty work around that, so this PR won't be sufficient.

Looks like we might just need to fork this.  Closing!

**Comment by black-snow** [comment]
Might be related to this change, after upgrading from 1.3.23 to 1.3.25 I receive:

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/SecureRequestCustomizer$SslAttributes
```
