### ISSUE TITLE
Create 1.0.0 to 1.1.0 Migration Guide

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#1926]
We should create a 1.0.x to 1.1.0 migration guide. Here are some things I've come across.

- Due to https://github.com/dropwizard/dropwizard/pull/1851, users must now add mockito as a test dependency

```xml
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-core</artifactId>
    <version>2.7.6</version>
    <scope>test</scope>
</dependency>
```

Else become susceptible to the following error:

```
java.lang.NoClassDefFoundError: org/mockito/Mockito
```

- Due to https://github.com/dropwizard/dropwizard/pull/1695, `Cli` no longer allows exceptions to propagate, (which is a net positive), but I did have to rewrite my tests to no longer trap for exceptions but examine stderr.

**Comment by arteam** [comment]
Good idea! We currently maintain upgrade guides in our [wiki](https://github.com/dropwizard/dropwizard/wiki). We could start the 1.1.0 guide there as well.

**Comment by jplock** [comment]
I created https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-1.0.x-to-1.1.x with a cut and paste from @nickbabcock's comments.

**Comment by nickbabcock** [comment]
We'll also need to include whatever breaking changes were introduced in https://github.com/dropwizard/dropwizard/pull/1871, no?

**Comment by jplock** [comment]
Closing this as we at least have a guide now  :)
