### PR TITLE
Upgrade to Jetty 9.3.5

### PR DESCRIPTION
**Pull request by arteam**
This PR ugrades Dropwizard baseline to Jetty 9.3.5. Relevant issue is #1036. 
It consists from several changes:

* `dropwizard-spdy` is removed, because it's not longer supported by Jetty 9.3. Its successor is HTTP 2.0 integration, which we wiil need to implement.
* Upgaded the Jetty dependency in the BOM file. 
* Added own `InstrumentConnectionFactory`, because `metrics` library doesn't support Jetty 9.3. See https://github.com/dropwizard/metrics/pull/823
* `BiDiGzipFilter` is moved to `BiDiGzipHandler`, because Jetty doesn't provide `GzipFilter` anymore.
Some parameters, that were accessible in the filter, are no longer exist. So, we had to remove them
from the handler configuration. 
* Finally, it looks like that Jetty now requires providing a path to a trust store in HTTPS configuration.
Even with disabled peer validation. I don't know a way to get it progmatically, so I provided a path that works on Linux systems (at least on Ubuntu-based). If anyone can provide a better solution, I will gladly hear about it.

### CODE REVIEW

**Comment by jplock** [comment]
@dropwizard/committers should we also get this merged in now? It'd be nice to start prepping 1.0.0 release candidates as we'll want to make sure its heavily tested.

**Comment by nickbabcock** [comment]
Awesome pull request, I'm a little hesitant about the trust store changes. I skimmed the Jetty 9.3 source code and it appears that it should still accept a null trust store, in which case will `SSLContext.init` will search for 

> the installed security providers will be searched for the highest priority implementation of the appropriate factory

**Comment by arteam** [comment]
I checked Jetty's [SslContextFactory](https://github.com/eclipse/jetty.project/blob/master/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java) one more time. It looks like that by default
Jetty loads a truststore as same as a keystore. But if we start an application, it fails with 

```java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.```

It looks like that JRE doesn't want to trust the specified in the keystore certificate. If we enable 
```yaml
validatePeers: false
``` 
in the configuration, then the application starts up without errors. I don't know, why this worked
previously. Anyway, looks like that enabling this option fixes the problem.

**Comment by arteam** [comment]
As a side-note: users of PKCS12 certificates would need to specify `trustStoreType`.

**Comment by nickbabcock** [comment]
Ok interesting, I'm not sure why it worked previously either. I wanted to play around with your branch but I'm unable to in Intellij, as various compilation errors crop up even after a fresh clone (it keeps wanting to use jetty 9.2.13). `mvn package` works fine though, so I'm unsure what the issue could be.

Also any reason not to use 9.3.6.v20151106?

**Comment by arteam** [comment]
> Ok interesting, I'm not sure why it worked previously either. I wanted to play around with your 
> branch |but I'm unable to in Intellij, as various compilation errors crop up even after a fresh clone 
> (it |keeps |wanting to use jetty 9.2.13). mvn package works fine though, so I'm unsure what the 
> issue |could be.

I believe, one need to perform `mvn clean install` on `dropwizard-bom` beforehand. Otherwise Maven will pull old `dropwizard-bom` snapshot from the repository.

> Also any reason not to use 9.3.6.v20151106?

No reason. I just started working on this update before than 9.3.6 came up.

**Comment by nickbabcock** [comment]
The bom trick fixed the issue. :+1:
