### ISSUE TITLE
Runtime Error on version 2.0.0 and Java 11

### ISSUE THREAD

**Issue by RohanNagar** [dropwizard/dropwizard#3084]
This code seems to work fine on Dropwizard 2.0.0 and Java 8, but when I compile and run on Java 11, I get an exception when starting up.

```java
public void run(ThunderConfiguration config, Environment env) {
    ThunderComponent component = DaggerThunderComponent.builder()
        .daoModule(new DaoModule(config.getDynamoConfiguration().getTableName()))
        .dynamoDbModule(new DynamoDbModule(config.getDynamoConfiguration()))
        .emailModule(new EmailModule(config.getEmailConfiguration()))
        .thunderModule(new ThunderModule(env.metrics(), config))
        .build();

    // Authentication
    env.jersey().register(new AuthDynamicFeature(new BasicCredentialAuthFilter.Builder<Key>()
            .setAuthenticator(component.getThunderAuthenticator())
            .setRealm("THUNDER - AUTHENTICATION")
            .buildAuthFilter()));

    env.jersey().register(new AuthValueFactoryProvider.Binder<>(Key.class));

    // HealthChecks
    env.healthChecks().register("DynamoDB", component.getDynamoDbHealthCheck());

    // Resources
    env.jersey().register(component.getUserResource());

    // Only register verification resource if it is enabled
    if (config.getEmailConfiguration().isEnabled()) {
      env.jersey().register(component.getVerificationResource());
    }
  }
```

Exception:

```
java.lang.NoSuchMethodError: 'java.lang.Class javassist.CtClass.toClass(java.lang.Class)'
	at io.dropwizard.jersey.DropwizardResourceConfig.register(DropwizardResourceConfig.java:170)
	at io.dropwizard.jersey.setup.JerseyEnvironment.register(JerseyEnvironment.java:36)
	at com.sanctionco.thunder.ThunderApplication.run(ThunderApplication.java:64)
	at com.sanctionco.thunder.ThunderApplication.run(ThunderApplication.java:27)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:79)
	at io.dropwizard.Application.run(Application.java:94)
	at com.sanctionco.thunder.ThunderApplication.main(ThunderApplication.java:30)
```

It looks like it's failing at `env.jersey().register(component.getUserResource());`. How should this be changed in order to work? I can't seem to find much info in the docs. Thanks in advance!

**Comment by roccoboi99** [comment]
Hey, I had the same issue when my project dependent on swagger. I guess some of your dependencies has transitive dependencies on old javassist.
As I use maven to build my project, I have to exclude the old dependency out of the swagger.

Here is how I did in pom.xml
`<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.26-GA</version>
</dependency>
<dependency>
    <groupId>io.swagger.core.v3</groupId>
    <artifactId>swagger-jaxrs2</artifactId>
    <version>2.1.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
        </exclusion>
    </exclusions>
</dependency>
`

**Comment by RohanNagar** [comment]
Awesome @roccoboi99 this worked. I have swagger in my project as well and seems like it was also causing issues. Thank you!
